### ISSUE TITLE
invalid syntax in genbank.py

### ISSUE THREAD

**Issue by courtherms** [linsalrob/genbank_to#1]
Hey, I have genbank_to installed in a conda environment, and when trying to run there is a syntax error in genbank.py:

 ```
Traceback (most recent call last):
  File "/home/chh/miniconda3/envs/genbank_to/bin/genbank_to", line 7, in <module>
    from GenBankToLib.main import run
  File "/home/chh/miniconda3/envs/genbank_to/lib/python3.5/site-packages/GenBankToLib/__init__.py", line 5, in <module>
    from .genbank import genbank_to_faa, genbank_to_fna, genbank_to_orfs, genbank_to_ptt, genbank_to_functions
  File "/home/chh/miniconda3/envs/genbank_to/lib/python3.5/site-packages/GenBankToLib/genbank.py", line 55
    loc = f"{start}_{stop}"
```

I'm afraid I am not experienced enough in python to understand why there's an error and fix it myself.

**Comment by linsalrob** [comment]
You need to make sure you are using a modern version of Python - at least 3.6 or higher. I suspect you are using python2. Try `python --version` to see what version you are currently using.
